version: '2'
services:
#    oori:
#      image: biotope/oori
#      environment:
#        - SERVER_PORT=9090
#        - CB_PORT=9090
#        - ENDPOINT_URL=http://fuseki:3030/odfData
#        - CB_HOSTNAME=biotope.iais.fraunhofer.de
#      ports:
#        - "9090:9090"
#        - "5005:5005"   # java debugging

#    fuseki:
#      build: fuseki/
#      ports:
#        - "3030:3030"

    o-mi-node:
      container_name: omi-node
      build: o-mi-node/
      ports:
       - "8080:8080"

#    dashboard-context-manager:
#      image: biotope/dashboard-context-manager
#      environment:
#        - SERVER_PORT=4040
#      ports:
#        - "4040:4040"

#    mongodata:
#      image: mongo
#      volumes:
#        - /data/db
#      command: --break-mongo

    mongodb:
      container_name: mongodb
#      build: mongodb/
      ports:
        - "27017:27017"
      image: mongo
      volumes:
        - './data/db:/data/db'
#      volumes_from:
#        - mongodata
#      command: -smallfiles --rest --auth

#    data-science:
#      image: jupyter/datascience-notebook
#      ports:
#        - "8888:8888"

    node-red:
      container_name: nodered
      build: node-red/
      ports:
        - "1880:1880"
      volumes:
        - "./modules:/usr/src/node-red/modules"
      links:
        - mongodb
        - o-mi-node

    smartmobility:
      container_name: smartmobility
      build: node-red/
      ports:
        - "3000:1880"
      volumes:
        - "./modules:/usr/src/node-red/modules"
      links:
        - mongodb
        - o-mi-node

    heatwavemitigation:
      container_name: heatwavemitigation
      build: node-red/
      ports:
        - "1883:1880"
      volumes:
        - "./modules:/usr/src/node-red/modules"
      links:
        - mongodb
        - o-mi-node

    smartcomobility:
      container_name: smartcomobility
      build: node-red/
      ports:
        - "1886:1880"
      volumes:
        - "./modules:/usr/src/node-red/modules"
      links:
        - mongodb
        - o-mi-node

   bottlebankcitizen:
      container_name: bottlebankcitizen
      build: node-red/
      ports:
        - "1884:1880"
      volumes:
        - "./modules:/usr/src/node-red/modules"
      links:
        - mongodb
        - o-mi-node

   bottlebankwastemanagement:
      container_name: bottlebankwastemanagement
      build: node-red/
      ports:
        - "1885:1880"
      volumes:
        - "./modules:/usr/src/node-red/modules"
      links:
        - mongodb
        - o-mi-node


    proxy:
      container_name: proxy
      image: proxy
      build:
        context: ./proxy
      ports:
        - "80:80"
