version: '2'
services:
    mongodb:
      ports:
        - "27017:27017"
      image: mongo
      volumes:
        - './data/db:/data/db'

    node-red:
      build: node-red/
      ports:
        - "1880:1880"
      volumes:
        - "./modules:/usr/src/node-red/modules"
      links:
        - mongodb

      # blazegraph:
      #   image: docker.io/lyrasis/blazegraph:2.1.4
      #   ports:
      #     - "8081:8080"
      #
      # oorcs:
      #   build: oorcs/
      #   ports:
      #     - "8080:8080"
      #     - "5005:5005"
